version: '3'
services:
  # Nginx Web server
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/web
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
  # PHP-FPM
  phpfpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/web
    restart: unless-stopped
  # Relational database - mariadb 10.3
  db:
    image: mariadb:10.3
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    command: --max_allowed_packet=32505856      # Set max_allowed_packet to 256M (or any other value)
    environment:
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=rtarf
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./flarum-db:/var/lib/mysql
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    restart: unless-stopped
  #phpmyadmin
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9000:80
    environment:
      - PMA_HOST=db
    restart: unless-stopped
    
    